travis:
  secure:
    BINSTAR_TOKEN: gLgCxQ658U48w8lQfjm43sCbR0QqQ3d/nrMNPuXURew1hIvFqUyzkRBYjbIPGPgJFezuesMLOjVX+mZsjwm8c0uicCP4EpgGyzHCNByhtxSR/nwmY42nBuUxdQp5/R5YWexpmQHSwhDU+SAfjMYELh76FiENRuMHAODKviOPbZJFyT6emgA1BdV3iefGw6ayXOrpRfm1hV3FRXAaeLrOtei9Pe2LqocveMV/98+hD7iXEFhNuhg67qaEbEg0iMqD2tQD9MY6UTbIsNDZQYnQ6WtcuLYatoUb2fkuK4FE3JGAEn5KrpEKKkoJe/TqGpBYCFVVJ3K3vLU4irxiB/bIEkuWKUVBBE86KQGapJPHvTdEHpmuxhHuoBF+gHm7NjLUMS/7J9s+UpE2VlDq9vCfz0Z7PMylVB0Q9iYuimaevZM3rusJ2yZeEJvMAZzmUeEAq5UlVsZc8h4J3Ipu1HWP9fY2l/CL71EWojr3gBNPk1hHqlleZdElAhBRTNME7lhlSYwvoAC9qt79YPImUkw5GlM3mVVUwn5ELLdIoJg30Zc/Fokp4KPYzRb6x/H7UkCdey+e9/PRTJvqY2deE2jSyMKh0jk1VevluEjaeOdM7OMZ376iZvLdlqzdOCPhmil9HnpaGkytsBoS27laXu2Em1z1gbwUf7mzhAr2K+u9ndA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
